name: Python Billing System CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check code formatting with Black
        run: black --check .

      - name: Check code quality with Ruff
        run: ruff check .

      - name: Compile Python files
        run: python -m compileall .

      - name: Run unit tests
        run: python -m unittest test_main.py -v 